var appRoot="./";
//document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"script/eui/eui.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/date.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/jquery.min.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/stcm.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/vue-router.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/vue.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/axios.min.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/utils.js'></script>");
document.write("<script type='text/javascript' language='javascript' src='"+appRoot+"js/loading.js'></script>");
document.write("<link rel='stylesheet' type='text/css' href='"+appRoot+"css/basic.css'></script>");
